#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/../.common.sh"

DOCKER_IMAGE=lateautumn233/nginx-full:certbot-node
docker pull "${DOCKER_IMAGE}"

# Test
echo -e "${BLUE}❯ ${CYAN}Testing backend ...${RESET}"
docker run --rm \
	-v "$(pwd)/backend:/app" \
	-v "$(pwd)/global:/app/global" \
	-w /app \
	"${DOCKER_IMAGE}" \
	sh -c 'yarn install && yarn eslint . && rm -rf node_modules'
echo -e "${BLUE}❯ ${GREEN}Testing Complete${RESET}"

# Build
echo -e "${BLUE}❯ ${CYAN}Building ...${RESET}"
docker build --pull --no-cache --compress \
	-t "lateautumn233:nginx-proxy-manager" \
	-f docker/Dockerfile \
	--build-arg "HTTP_PROXY=http://192.168.31.161:7897/" \
    --build-arg "HTTPS_PROXY=http://192.168.31.161:7897/" \
    --build-arg "NO_PROXY=localhost,127.0.0.1,.example.com" \
	--build-arg TARGETPLATFORM=linux/amd64 \
	--build-arg BUILDPLATFORM=linux/amd64 \
	--build-arg BUILD_VERSION="${BUILD_VERSION}" \
	--build-arg BUILD_COMMIT="${BUILD_COMMIT}" \
	--build-arg BUILD_DATE="$(date '+%Y-%m-%d %T %Z')" \
	.
echo -e "${BLUE}❯ ${GREEN}Building Complete${RESET}"
